
test_that("read_chroms can read Varian SMS", {
  skip_on_cran()
  skip_if_not_installed("chromConverterExtraTests")

  path_sms <- system.file("STRD15.SMS", package = "chromConverterExtraTests")
  path_mzml <- system.file("STRD15.mzML", package = "chromConverterExtraTests")

  skip_if_not(file.exists(path_sms))
  skip_if_not(file.exists(path_mzml))

  tmp <- tempdir()
  # must be in long format to export successfully
  x <- read_chroms(path_sms, progress_bar = FALSE, export_format = "mzml",
                   data_format = "long", path_out = tmp, force = TRUE)[[1]]

  path_mzml_cc <- fs::path(tmp, attr(x$MS1, "sample_name"), ext = "mzML")
  on.exit(unlink(path_mzml_cc))

  x1 <- read_chroms(path_mzml, format_in = "mzml", data_format = "long",
                    progress_bar = FALSE)[[1]]
  x2 <- read_chroms(path_mzml_cc, format_in = "mzml", progress_bar = FALSE,
                    format_out = "data.frame")[[1]]

  # check equality of mass spec scans
  ms1_mzml <- x1$MS1[,-4]
  ms1_mzml$rt <- ms1_mzml$rt / 1000
  expect_equal(as.data.frame(x$MS1), ms1_mzml, tolerance = .0000001,
               ignore_attr = TRUE)
  expect_equal(as.data.frame(x$MS1), x2$MS1[,c(1:3)], ignore_attr = TRUE)

  # check equality of TIC
  expect_equal(x$TIC[, "rt"], x1$TIC$rt/1000, tolerance = .000001)
  # there is a slight discrepancy with the TICs generated by OpenChrom but mine
  # seem to be correct...?
  expect_equal(x$TIC[, "intensity"], x1$TIC$int, tolerance = .000001)
  # expect_equal(x$TIC, x2$TIC[,-3], ignore_attr = FALSE)

  # check equality of BPC
  expect_equal(x$BPC[, "rt"], x1$BPC$rt/1000, tolerance = .000001)
  expect_equal(x$BPC[, "intensity"], x1$BPC$int)

  # check metadata
  expect_equal(attr(x$TIC, "software_name"), "MS Workstation (Upgrade)")
  expect_equal(attr(x$TIC, "no_scans"), 3432)
  expect_equal(attr(x$TIC, "sample_name"), "STRD15")
  expect_equal(attr(x$TIC, "ms_params")$max_ric_scan, 1445)
  expect_equal(attr(x$TIC, "ms_params")$max_ric_val, 39285)
  expect_equal(attr(x$TIC, "ms_params")$max_ionization_time, c(0, 25000))
  expect_equal(attr(x$TIC, "ms_params")$temp_trap, 150)
  expect_equal(attr(x$TIC, "ms_params")$temp_manifold, 50)
  expect_equal(attr(x$TIC, "ms_params")$temp_transferline, 250)
  expect_equal(attr(x$TIC, "ms_params")$axial_modulation, 4)
  expect_equal(attr(x$TIC, "data_format"), "long")
  expect_equal(attr(x$BPC, "data_format"), "long")
  expect_equal(attr(x$MS1, "data_format"), "long")

  # attr(x$MS1, "run_datetime") # should be 8/8/2014 8:50 PM - 9:20 PM
  expect_equal(x2$metadata$source_file, basename(attr(x$MS1,"source_file")))
  # expect_equal(x2$metadata$timestamp, attr(x$MS1,"run_datetime")[1])
})

test_that("read_varian_peaklist function works", {
  skip_on_cran()
  skip_if_not_installed("chromConverterExtraTests")

  path <- system.file("varian_peaklist.csv",
                      package = "chromConverterExtraTests")
  skip_if_not(file.exists(path))

  x <- read_varian_peaklist(path)
  expect_s3_class(x, "data.frame")
  expect_equal(dim(x), c(46476, 15))
})

test_that("read_chroms can write Varian SMS to CDF", {
  skip_if_not_installed("ncdf4")
  skip_on_cran()
  skip_if_not_installed("chromConverterExtraTests")

  path_sms <- system.file("STRD15.SMS", package = "chromConverterExtraTests")
  skip_if_not(fs::file_exists(path_sms))

  tmp <- tempdir()

  path_cdf <- fs::path(tmp, fs::path_ext_remove(basename(path_sms)),
                       ext = "cdf")
  on.exit(unlink(path_cdf))

  x <- read_chroms(path_sms, path_out = tmp, export_format = "cdf",
                   data_format = "long", progress_bar = FALSE, force = TRUE)[[1]]

  x3 <- read_cdf(path_cdf, data_format = "long", format_out = "data.frame")

  x3$MS1$rt <- x3$MS1$rt/60
  x3$TIC$rt <- x3$TIC$rt/60

  expect_equal(as.data.frame(x$MS1), x3$MS1, ignore_attr = TRUE,
               tolerance = .0000001)
  expect_equal(as.data.frame(x$TIC), x3$TIC, ignore_attr = TRUE,
               tolerance = .0000001)
  expect_equal(attr(x3$MS1, "run_datetime"), attr(x$MS1, "run_datetime")[1])
  expect_equal(attr(x3$MS1, "time_unit"), "Seconds")
  expect_equal(attr(x3$MS1, "detector"), "MS")
  expect_equal(attr(x3$MS1, "sample_name"), "STRD15")
})

# Synthetic checks for the 'Varian SMS' variable-length integer encoding.
# These need no external file, so they cover the branches that the sample files
# in `chromConverterExtraTests` do not exercise: within the MS regions of
# `STRD15.SMS` and `DCM1.SMS` the leading nibble never exceeds `C`, leaving the
# 27/28-bit rules for `d` = D, E and F untested by real data.

# Encode `value` as a token with leading nibble `d`, big-endian, with the low
# bits carried in the trailing bytes. For d < 4 the token is a single byte and
# the nibble is part of the value itself, so `d` must be the value's high
# nibble.
sms_token <- function(d, value){
  len <- 1L + d %/% 4L
  if (len == 1L){
    stopifnot(value %/% 16L == d)
    return(as.raw(value))
  }
  bytes <- integer(len)
  for (i in seq_len(len - 1L)){
    bytes[len - i + 1L] <- bitwAnd(bitwShiftR(value, 8L * (i - 1L)), 0xFFL)
  }
  bytes[1] <- bitwOr(bitwShiftL(d, 4L),
                     bitwShiftR(value, 8L * (len - 1L)))
  as.raw(bytes)
}

test_that("MS stream decoder handles every token length class", {
  # one (m/z delta, intensity) pair per length class, then the scan terminator
  pairs <- list(c(d = 2, v = 0x25),        # 1 byte,  full byte
                c(d = 5, v = 0x1234),      # 2 bytes, low 13 bits
                c(d = 9, v = 0x1ABCDE),    # 3 bytes, low 21 bits
                c(d = 12, v = 0x5ABCDEF),  # 4 bytes, low 27 bits
                c(d = 15, v = 0xFABCDEF))  # 4 bytes, low 28 bits
  raw_stream <- c(unlist(lapply(pairs, function(p)
    c(sms_token(p[["d"]], p[["v"]]), sms_token(1L, 0x11)))),
    as.raw(c(0, 0)))

  path <- tempfile()
  on.exit(unlink(path), add = TRUE)
  writeBin(raw_stream, path)
  f <- file(path, "rb")
  on.exit(close(f), add = TRUE)

  # `d` = 12 and 15 assemble to 3.3e9 and 4.3e9, past `.Machine$integer.max`,
  # so these also cover the 4-byte overflow path: the lead byte has to be masked
  # before the token is assembled, or the value comes back `NA`.
  expect_no_warning(
    x <- read_varian_ms_stream(f, n_scans = 1, flen = file.size(path),
                               format_out = "data.frame")
  )

  expect_equal(nrow(x), length(pairs))
  expect_true(all(x$scan == 1))
  # m/z is delta-encoded, so the column is the running sum of the deltas / 10
  expect_equal(x$mz, cumsum(vapply(pairs, `[[`, numeric(1), "v")) / 10)
  expect_equal(x$intensity, rep(0x11, length(pairs)))
  expect_false(anyNA(x))
})

test_that("read_varian_offsets reads the full fixed-width directory", {
  skip_on_cran()
  skip_if_not_installed("chromConverterExtraTests")

  path <- system.file("STRD15.SMS", package = "chromConverterExtraTests")
  skip_if_not(file.exists(path))
  f <- file(path, "rb")
  on.exit(close(f), add = TRUE)
  x <- read_varian_offsets(f)

  expect_equal(nrow(x), 12)
  # record 3 begins at 2411520, a multiple of 256: its leading null byte used to
  # be mistaken for name padding, shifting every field in the record by one
  expect_equal(x[3, ], data.frame(start = 2411520, end = 2411610, number = 3,
                                  name = "ModuleInfo:B.44"),
               ignore_attr = TRUE)
  expect_equal(x$name[1:2], c("DIRECTORY", "MSData"))
  # sections tile the file without gaps
  expect_equal(x$start[-1], x$end[-nrow(x)])
})

test_that("read_varian_offsets reads entries past InjectionLog", {
  skip_on_cran()
  skip_if_not_installed("chromConverterExtraTests")

  path <- system.file("DCM1.SMS", package = "chromConverterExtraTests")
  skip_if_not(file.exists(path))
  f <- file(path, "rb")
  on.exit(close(f), add = TRUE)
  x <- read_varian_offsets(f)

  # InjectionLog is entry 12 but not the last one here
  expect_equal(nrow(x), 22)
  expect_equal(x$name[12], "InjectionLog")
  expect_equal(x[22, c("start", "end", "name")],
               data.frame(start = 2776816, end = 3152076, name = "MSResults:h4"),
               ignore_attr = TRUE)
  expect_equal(x$end[22], file.size(path))
})

test_that("MS stream is bounded by the MSData section, not the file", {
  skip_on_cran()
  skip_if_not_installed("chromConverterExtraTests")

  # DCM1.SMS carries ~2 MB of peak tables and results after the spectra, so the
  # bound matters there; STRD15.SMS ends just past MSData and should be a no-op.
  path <- system.file("DCM1.SMS", package = "chromConverterExtraTests")
  skip_if_not(file.exists(path))
  f <- file(path, "rb")
  on.exit(close(f), add = TRUE)
  offsets <- read_varian_offsets(f)
  ms_end <- offsets$end[offsets$name == "MSData"]

  expect_lt(ms_end, file.size(path))

  # reading to the section end and to EOF must agree
  seek_to_spectra <- function(f){
    meta <- read_varian_msdata_header(f)
    chroms <- read_varian_chromatograms(f, n_time = meta$n_scan,
                                        format_out = "matrix",
                                        data_format = "long")
    skip_null_bytes(f)
    nrow(chroms) - max(which(chroms[, "tic"] == 0))
  }
  n_scans <- seek_to_spectra(f)
  bounded <- read_varian_ms_stream(f, n_scans = n_scans, flen = ms_end)
  seek(f, 0)
  n_scans <- seek_to_spectra(f)
  unbounded <- read_varian_ms_stream(f, n_scans = n_scans,
                                     flen = file.size(path))

  expect_equal(bounded, unbounded)
})

test_that("read_varian_sms still works when metadata is not requested", {
  skip_on_cran()
  skip_if_not_installed("chromConverterExtraTests")

  path <- system.file("DCM1.SMS", package = "chromConverterExtraTests")
  skip_if_not(file.exists(path))

  x <- read_varian_sms(path, read_metadata = FALSE)
  y <- read_varian_sms(path, read_metadata = TRUE)
  expect_equal(as.matrix(x$MS1), as.matrix(y$MS1), ignore_attr = TRUE)
  expect_null(attr(x$MS1, "sample_name"))
  expect_equal(attr(y$MS1, "sample_name"), "DCM1")
})

test_that("acquisition timestamps are read correctly", {
  skip_on_cran()
  skip_if_not_installed("chromConverterExtraTests")

  path <- system.file("STRD15.SMS", package = "chromConverterExtraTests")
  skip_if_not(file.exists(path))
  f <- file(path, "rb")
  on.exit(close(f), add = TRUE)
  meta <- read_varian_msdata_header(f)

  # matches the startTimeStamp OpenChrom writes for this sample
  # ("2014-08-08T23:50:55.000-04:00")
  expect_equal(meta$acquisition_start,
               as.POSIXct("2014-08-09 03:50:55", tz = "UTC"))
  expect_equal(meta$acquisition_end,
               as.POSIXct("2014-08-09 04:20:54", tz = "UTC"))

  # the interval between them is the span of the chromatogram
  chroms <- read_varian_chromatograms(f, n_time = meta$n_scan,
                                      format_out = "matrix",
                                      data_format = "long")
  span <- difftime(meta$acquisition_end, meta$acquisition_start, units = "mins")
  expect_equal(as.numeric(span), max(chroms[, "rt"]) - min(chroms[, "rt"]),
               tolerance = 0.001)
})

test_that("InjectionLog metadata is attached", {
  skip_on_cran()
  skip_if_not_installed("chromConverterExtraTests")

  path <- system.file("STRD15.SMS", package = "chromConverterExtraTests")
  skip_if_not(file.exists(path))

  x <- read_varian_sms(path)
  expect_equal(attr(x$TIC, "instrument"), "Varian GC/MS #1")
  expect_equal(attr(x$TIC, "method"),
               "c:\\varianws\\methods\\wax column\\wax-voc.mth")
  expect_equal(attr(x$TIC, "run_datetime"),
               as.POSIXct("2014-08-09 03:50:55", tz = "UTC"))

  # the injection time recorded in the InjectionLog agrees with the MSData header
  f <- file(path, "rb")
  on.exit(close(f), add = TRUE)
  inj <- read_varian_injection_log(f, read_varian_offsets(f))
  expect_equal(inj$injection_time, attr(x$TIC, "run_datetime"))
  expect_equal(inj$os_version, "WinNT 5.1.2600 Service Pack 2")
})

test_that("read_varian_sms works with `format_out = \"data.table\"`", {
  skip_on_cran()
  skip_if_not_installed("chromConverterExtraTests")

  path <- system.file("STRD15.SMS", package = "chromConverterExtraTests")
  skip_if_not(file.exists(path))

  # this used to fail outright: the scan column was subset with `MS1[, 1]`,
  # which returns a one-column `data.table` and so was read as a join key
  # rather than as row indices. The TIC and BPC intensity column also came out
  # named `tic`/`bpc`.
  x <- read_varian_sms(path, format_out = "data.table", data_format = "long")

  expect_s3_class(x$MS1, "data.table")
  expect_equal(colnames(x$MS1), c("rt", "mz", "intensity"))
  expect_equal(colnames(x$TIC), c("rt", "intensity"))
  expect_equal(colnames(x$BPC), c("rt", "intensity"))

  expect_equal(dim(x$MS1), c(935314L, 3L))
  expect_equal(unlist(x$MS1[1, ]), c(rt = 6.483867, mz = 60, intensity = 1),
               tolerance = 1e-6)
  expect_equal(dim(x$TIC), c(3432L, 2L))
})

test_that("read_null_terminated rejects non-text bytes", {
  b <- as.raw(c(0x41, 0x42, 0x00, 0xFF, 0xFE, 0x00))
  expect_equal(read_null_terminated(b, 0), "AB")
  expect_null(read_null_terminated(b, 3))   # not printable
  expect_null(read_null_terminated(b, 2))   # empty
  expect_null(read_null_terminated(b, 99))  # past the end
})
